### PR TITLE
Add openjdk headless jre 8 in a docker container.

### LINKED ISSUE #1: Add openjdk headless jre 8 in a docker container.
This should use https://github.com/lynxtp/docker-ubuntu as its base and provide `java` as the default command. This will be a minimal container sufficient to run uberjars in production.

### PR DESCRIPTION
**Pull request by tvaughan**
Fixes #1. This pull-request will be merged into branch `8` not `master`. Our [automated builds](https://hub.docker.com/r/lynxtp/openjdk-jre/~/settings/automated-builds) create containers with version numbers that match their branch name. This means that each time we push to branch `8` a new container will automatically be built and tagged as version number `8`.

### CODE REVIEW

**Comment by stevebrewer** [comment]
What's the reasoning for openjdk vs. oracle?

**Comment by stevebrewer** [comment]
I think this answers my question: http://askubuntu.com/questions/437752/openjdk-oracle-is-better

**Comment by tvaughan** [comment]
> What's the reasoning for openjdk vs. oracle?

Yeah, there's not much of a difference between the two implementations now. Kinda like Chromium and Chrome, except with fewer differences. But openjdk has much more liberal licensing terms and as such is packaged really well for Ubuntu, unlike Oracle's proprietary jdk.

**Comment by stevebrewer** [comment]
:+1:

**Pull request merged**
